### ISSUE TITLE
Not compatible with bootstrap v2

### ISSUE THREAD

**Issue by maxaudrin** [webjars/bootstrap-switch#10]
Hello,

I'm using bootstrap v2.3.2. When I add a dependency to bootstrap-switch webjar the website style break up because of the internal dependency to bootstrap v3. Can you remove this dependency and let the user choose the bootstrap version ? Or how can I force the use of bootstrap v2 ?

Thanks !

**Comment by jamesward** [comment]
Do you think the transitive dependency defined in this WebJar is inconsistent with the upstream?  If so, let's fix that.  If not, then you can tell you build tool to exclude the transitive dependency but the instructions for that depend on your build tool.

**Comment by maxaudrin** [comment]
Hi James,

I'm using SBT and I've just discovered that SBT can exclude transitive dependencies. I just did a test in excluding bootstrap v3 from this webjar and it was working as expected. Sorry for the loss of time and thanks for the reactivity !
